[[redirects]]
  from = "https://diario.netlify.app/diario/"
  to = "https://diario.netlify.app/%F0%9F%93%98/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/ler%20diario/"
  to = "https://diario.netlify.app/%F0%9F%93%98/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/ler%20diario/"
  to = "https://diario.netlify.app/%F0%9F%93%98/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/diary/"
  to = "https://diario.netlify.app/%F0%9F%93%98/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/"
  to = "https://diario.netlify.app/%F0%9F%93%98/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/mlp/*"
  to = "https://diario.netlify.app/my_little_pony ğŸ¦„/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/my%20little%20pony/*"
  to = "https://diario.netlify.app/my_little_pony ğŸ¦„/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/w/"
  to = "https://diario.netlify.app/watch ğŸ‘/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/watch%20history/"
  to = "https://diario.netlify.app/watch ğŸ‘/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/wh/"
  to = "https://diario.netlify.app/watch ğŸ‘/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/assistidos/"
  to = "https://diario.netlify.app/watch ğŸ‘/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/watch/"
  to = "https://diario.netlify.app/watch ğŸ‘/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/musica/"
  to = "https://diario.netlify.app/music ğŸµ/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/m/"
  to = "https://diario.netlify.app/music ğŸµ/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/music/"
  to = "https://diario.netlify.app/music ğŸµ/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/jogos/"
  to = "https://diario.netlify.app/games ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/jogo/"
  to = "https://diario.netlify.app/games ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/game/"
  to = "https://diario.netlify.app/games ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/games/"
  to = "https://diario.netlify.app/games ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/foobar/"
  to = "https://diario.netlify.app/foobar_albums ğŸµ/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/f_a/"
  to = "https://diario.netlify.app/foobar_albums ğŸµ/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/fa/"
  to = "https://diario.netlify.app/foobar_albums ğŸµ/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/foobar_albums/"
  to = "https://diario.netlify.app/foobar_albums ğŸµ/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/t_t/"
  to = "https://diario.netlify.app/terraria_talk ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/tt/"
  to = "https://diario.netlify.app/terraria_talk ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/terraria%20talk/"
  to = "https://diario.netlify.app/terraria_talk ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/terraria/"
  to = "https://diario.netlify.app/terraria_talk ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/terraria_talk/"
  to = "https://diario.netlify.app/terraria_talk ğŸ®/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/tarefas/"
  to = "https://diario.netlify.app/tasks ğŸ—’/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/tasks - tarefas/"
  to = "https://diario.netlify.app/tasks ğŸ—’/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/tasks/"
  to = "https://diario.netlify.app/tasks ğŸ—’/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/ano%202018/"
  to = "https://diario.netlify.app/years ğŸ“…/2018/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/ano%202019/"
  to = "https://diario.netlify.app/years ğŸ“…/2019/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/year%202018/"
  to = "https://diario.netlify.app/years ğŸ“…/2018/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/year%202019/"
  to = "https://diario.netlify.app/years ğŸ“…/2019/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/2018/"
  to = "https://diario.netlify.app/years ğŸ“…/2018/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/2019/"
  to = "https://diario.netlify.app/years ğŸ“…/2019/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/years/2018/"
  to = "https://diario.netlify.app/years ğŸ“…/2018/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/years/2019/"
  to = "https://diario.netlify.app/years ğŸ“…/2019/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/2020/"
  to = "https://diario.netlify.app/years ğŸ“…/2020/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/years/2020/"
  to = "https://diario.netlify.app/years ğŸ“…/2020/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/years/2020/"
  to = "https://diario.netlify.app/years ğŸ“…/2020/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/ya/"
  to = "https://diario.netlify.app/years ğŸ“…/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/anos/"
  to = "https://diario.netlify.app/years ğŸ“…/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/years/"
  to = "https://diario.netlify.app/years ğŸ“…/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/s_h/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/sh/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/hist/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historias/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historia/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/hist%C3%B3rias/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories_historias/"
  to = "https://diario.netlify.app/stories_historias ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/nw/"
  to = "https://diario.netlify.app/new_world âŠ¡/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/n_w/"
  to = "https://diario.netlify.app/new_world âŠ¡/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/new%20world/"
  to = "https://diario.netlify.app/new_world âŠ¡/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/new_world/"
  to = "https://diario.netlify.app/new_world âŠ¡/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pqnt/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historias/pequenata/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historias/pqnt/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historia/pequenata/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historia/pqnt/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/littletato/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/littletato/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/pequenata/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/pqnt/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/pequenata/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/pqnt/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/litt/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/littletato/*"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/lp/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pl/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pequenitas/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pequenata/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pequenata/en-us/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pequenata/pt-br/"
  to = "https://diario.netlify.app/pequenata ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/hist/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/hist/sl/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/sl/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historia/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historias/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historias/sl/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/sl/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/sl/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/nw/sl/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/spacel/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/new%20world/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/new_world/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/nw/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/n_w/spaceliving/"
  to = "https://diario.netlify.app/new_world âŠ¡/spaceliving ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/nazzevo/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/nazzevo/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historia/nazzevo/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historias/nazzevo/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/irm%C3%A3os_nazzevo/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/lulu%20e%20zaque/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/lulu_e_zaque/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/luluxzaque/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/luluxizaque/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/luluizaque/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/lulueizaque/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/lei/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/l&i/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/nazzevo/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/nazzevo/en-us/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/nazzevo/pt-br/"
  to = "https://diario.netlify.app/nazzevo ğŸ“˜/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/story/luiza/"
  to = "https://diario.netlify.app/luiza/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/stories/luiza/"
  to = "https://diario.netlify.app/luiza/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historia/luiza/"
  to = "https://diario.netlify.app/luiza/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/historias/luiza/"
  to = "https://diario.netlify.app/luiza/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/eu/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/me/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pages/me/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/pages/eu/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/izaque/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/isaque/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/isaac/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/sobre%20mim/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/about%20me/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/sobre_mim/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/about_me/"
  to = "https://diario.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://diario.netlify.app/sinceramenteizaque/"
  to = "https://diario.netlify.app/yourstruly_izaque/"
  status = 301
  force = true

[[plugins]]
package = "@netlify/plugin-sitemap"