[[redirects]]
  from = "https://thestake2.netlify.app/"
  to = "https://thestake2.netlify.app/websites/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/read%20diary/"
  to = "https://thestake2.netlify.app/Diary/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/ler%20diario/"
  to = "https://thestake2.netlify.app/Diary/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/mlpfim/"
  to = "https://thestake2.netlify.app/My%20Little%20Pony/Friendship%20Is%20Magic/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/my%20little%20pony%20friendship%20is%20magic/"
  to = "https://thestake2.netlify.app/My%20Little%20Pony/Friendship%20Is%20Magic/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/w/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/wh/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/assistidos/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/watch/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/watch_history/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/watch%20%F0%9F%91%81/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/musica/"
  to = "https://thestake2.netlify.app/music/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/m/"
  to = "https://thestake2.netlify.app/music/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/jogos/"
  to = "https://thestake2.netlify.app/games/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/jogo/"
  to = "https://thestake2.netlify.app/games/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/game/"
  to = "https://thestake2.netlify.app/games/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/foobar/"
  to = "https://thestake2.netlify.app/foobar_albums/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/f_a/"
  to = "https://thestake2.netlify.app/foobar_albums/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/fa/"
  to = "https://thestake2.netlify.app/foobar_albums/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/tarefas/"
  to = "https://thestake2.netlify.app/tasks/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2018/"
  to = "https://thestake2.netlify.app/2018/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2019/"
  to = "https://thestake2.netlify.app/2019/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2020/"
  to = "https://thestake2.netlify.app/2020/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2021/"
  to = "https://thestake2.netlify.app/2021/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/anos/"
  to = "https://thestake2.netlify.app/years/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years%20%F0%9F%93%85/"
  to = "https://thestake2.netlify.app/years/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/hist%C3%B3rias/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/nw/"
  to = "https://thestake2.netlify.app/New World/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/n_w/"
  to = "https://thestake2.netlify.app/New World/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/new%20world/"
  to = "https://thestake2.netlify.app/New World/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/pqnt/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/pqnt/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/pqnt/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/stories/littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/pqnt/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/littletato/*"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/pequenata/en-us/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/pequenata/pt-br/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/A%20Vida%20de%20Pequenata/"
  to = "https://thestake2.netlify.app/The%20Life%20of%20Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/spaceliving/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/hist/sl/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/sl/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/spaceliving/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/spaceliving/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/stories/spaceliving/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/sl/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/stories/sl/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/sl/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/nw/sl/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/spaceliving/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/new_world%20%E2%8A%A1/spaceliving%20%F0%9F%93%98/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/New_World/SpaceLiving/"
  to = "https://thestake2.netlify.app/New World/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/stories/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/irm%C3%A3os_bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/bulkan/en-us/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/bulkan/pt-br/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/nazzevo%20%F0%9F%93%98/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/A%20Hist%C3%B3ria%20dos%20Irm√£os%20Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/O%20Segredo%20dos%20Cristais/"
  to = "https://thestake2.netlify.app/The Secret of the Crystals/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Ilha%20Deserta/"
  to = "https://thestake2.netlify.app/Desert Island/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/eu/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/me/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/izaque/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/isaac/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/sobre%20mim/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/about%20me/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/sobre_mim/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/about_me/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[plugins]]
package = "@netlify/plugin-sitemap"